// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc151.DeepSpace2019.subsystems;

import org.usfirst.frc151.DeepSpace2019.RobotMap;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;


/**
 *
 */
public class Hatch extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private Compressor compressor;
    private DoubleSolenoid hatchArm;
    private DoubleSolenoid beak;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public Hatch() {
        try {
            beak = new DoubleSolenoid(RobotMap.BEAK_SOLENOID_PORT_CLOSE, RobotMap.BEAK_SOLENOID_PORT_OPEN);
            addChild("Beak", beak);
        } catch (Exception e) {
            System.out.println("!!!ERROR:beak solenoid missing");
        }
       

        hatchArm = new DoubleSolenoid(RobotMap.ARM_SOLENOID_PORT_CLOSE, RobotMap.ARM_SOLENOID_PORT_OPEN);
        addChild("Arm", hatchArm);

        compressor = new Compressor(RobotMap.COMPRESSOR);
        addChild("Compressor", compressor);
        }

    
    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void extendArm() {
        hatchArm.set(Value.kForward);
    }

    public void retractArm() {
        hatchArm.set(Value.kReverse);
    }

    public void extendBeak() {
        beak.set(Value.kForward);
    }

    public void retractBeak() {
        beak.set(Value.kReverse);
    }

    public void compressorOn() {
        compressor.setClosedLoopControl(true);
    }

    public void compressorOff() {
        compressor.setClosedLoopControl(false);
    }
}

